---
# Source: retail-store-sample-catalog-chart/templates/mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: catalog-db
  namespace: catalog
data:
  username: "Y2F0YWxvZw=="
  password: "emdBeE9YcWIzY2U5T2I2WQ=="