---
# Source: retail-store-sample-orders-chart/templates/postgresql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: orders-db
  namespace: orders
data:
  username: "b3JkZXJz"
  password: "bENXYkhKazlBbjNBbWhBMg=="