name: AWS example workflow
on:
  workflow_dispatch:
env:
  AWS_REGION : "ap-southeast-1"
permissions:
  id-token: write
  contents: read
jobs:
  ListS3:
    runs-on: ubuntu-latest
    environment: poc
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4        
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::711387113538:role/AB3-GitHub-PipelineAccess
          role-session-name: ab3-retail-store-sample
          aws-region: ${{ env.AWS_REGION }}
      # Upload a file to AWS s3
      - name: List S3
        run: |
          aws s3 ls
